#callbacks
# [[on-window-detected]]
#     run = ['exec-and-forget sketchybar --trigger aerospace_new_window']

# on-focus-changed = ['exec-and-forget sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE']

# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
    'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

# exec-on-workspace-change = ['/bin/bash', '-c',
#     'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
# ]

# Start AeroSpace at login
start-at-login = true 

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
# enable-normalization-flatten-containers = true
# enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true 

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'dvorak'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     10
    outer.top =        10
    outer.right =      10

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    # See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
    # You can uncomment the following lines to open up terminal with alt + enter shortcut
    # (like in i3)
    # alt-enter = '''exec-and-forget osascript -e '
    # tell application "Terminal"
    #     do script
    #     activate
    # end tell'
    # '''

    # modes
    end = ['mode navigation', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=navigation']
    shift-end = ['mode service', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=service']

[mode.navigation.binding]

    space = ['exec-and-forget open /Applications/Raycast.app']
    enter = ['exec-and-forget kitty']
    q = ['close --quit-if-last-window']

    left = 'focus left'
    down = 'focus down'
    up = 'focus up'
    right = 'focus right'

    c = ['workspace C']
    g = ['workspace G']
    r = ['workspace R']

    h = ['workspace H']
    t = ['workspace T']
    n = ['workspace N']
    
    m = ['workspace M']
    w = ['workspace W']
    v = ['workspace V']

    a = ['workspace A']
    o = ['workspace O']
    e = ['workspace E']
    u = ['workspace U']

    tab = 'workspace-back-and-forth'

    esc = ['mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
    end = ['mode moving', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=moving']

[mode.moving.binding]
    left = 'move left'
    down = 'move down'
    up = 'move up'
    right = 'move right'

    c = ['move-node-to-workspace C']
    g = ['move-node-to-workspace G']
    r = ['move-node-to-workspace R']

    h = ['move-node-to-workspace H']
    t = ['move-node-to-workspace T']
    n = ['move-node-to-workspace N']
    
    m = ['move-node-to-workspace M']
    w = ['move-node-to-workspace W']
    v = ['move-node-to-workspace V']

    a = ['move-node-to-workspace A']
    o = ['move-node-to-workspace O']
    e = ['move-node-to-workspace E']
    u = ['move-node-to-workspace U']

    comma = 'move-workspace-to-monitor left'
    period = 'move-workspace-to-monitor right'

    end = ['mode layout', 'exec-and-forget sketchybar --trigger aerospace_mode_change mode=layout']
    esc = ['mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change mode=main']

[mode.layout.binding]
    up = 'resize smart +50'
    down = 'resize smart -50'

    comma = ['layout tiles horizontal vertical']
    period = ['layout accordion horizontal vertical']

    esc = ['mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = ['reload-config', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=main']
    r = ['flatten-workspace-tree']
    f = ['layout floating tiling']

    alt-shift-left = ['join-with left']
    alt-shift-down = ['join-with down']
    alt-shift-up = ['join-with up']
    alt-shift-right = ['join-with right']

    down = 'volume down'
    up = 'volume up'
    # todo
    # p = play
    # s = stop
    shift-down = ['volume set 0']
